# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    container_name: postgres_container
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: apiusuario
      POSTGRES_DB: apiusuario
      POSTGRES_PASSWORD: 123456
      PGDATA: ./postgres
    networks:
      - api-usuario
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rafael.ortiz.barrera@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - api-usuario
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 80:80

networks:
  api-usuario:
    driver: bridge
volumes:
  postgres:
    external: true
  pgadmin: